// services/mockBikeData.js

// 1. Define Bike Types (Enum-like)
export const BikeType = {
  MOUNTAIN: "Mountain",
  ROAD: "Road",
  CITY: "City",
  CARGO: "Cargo",
  HYBRID: "Hybrid"
};

// 2. Define Imaginary Suppliers
const SUPPLIERS = [
  { id: "sup-1", name: "VoltFleet Sydney", location: "Sydney CBD" },
  { id: "sup-2", name: "E-Motion Rentals", location: "Kensington" },
  { id: "sup-3", name: "GreenWheelz", location: "Bondi Junction" },
  { id: "sup-4", name: "Urban Rider Co.", location: "Surry Hills" }
];

// 3. The Master List (20 Bikes)
export const MOCK_BIKES = [
  // --- GROUP A: Top Rated ---
  {
    id: "b1",
    title: "Apex Predator X1",
    subtitle: "$150/week",
    price: 150,
    status: "Active",
    startDate: "2026-01-28",
    endDate: "2026-02-10",
    meta: "Jan 28 - Feb 10",
    type: BikeType.MOUNTAIN,
    isVerified: true,
    rating: 4.9,
    reviewCount: 42,
    image: require("../assets/images/SplashLogo.png"), 
    supplier: SUPPLIERS[0],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b2",
    title: "Cargo King 500",
    subtitle: "$200/week",
    price: 200,
    status: "Upcoming",
    startDate: "2026-02-15",
    endDate: "2026-02-20",
    meta: "Feb 15 - Feb 20",
    type: BikeType.CARGO,
    isVerified: true,
    rating: 5.0,
    reviewCount: 15,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[1],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b3",
    title: "Road Warrior Pro",
    subtitle: "$180/week",
    price: 180,
    status: "Active",
    startDate: "2026-02-01",
    endDate: "2026-02-07",
    meta: "Feb 01 - Feb 07",
    type: BikeType.ROAD,
    isVerified: true,
    rating: 4.8,
    reviewCount: 89,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[2],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b4",
    title: "Urban Glide S",
    subtitle: "$110/week",
    price: 110,
    status: "Upcoming",
    startDate: "2026-03-01",
    endDate: "2026-03-05",
    meta: "Mar 01 - Mar 05",
    type: BikeType.CITY,
    isVerified: true,
    rating: 4.9,
    reviewCount: 120,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[3],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b5",
    title: "Summit Seeker",
    subtitle: "$165/week",
    price: 165,
    status: "Active",
    startDate: "2026-02-10",
    endDate: "2026-02-15",
    meta: "Feb 10 - Feb 15",
    type: BikeType.MOUNTAIN,
    isVerified: true,
    rating: 4.8,
    reviewCount: 34,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[0],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },

  // --- GROUP B: Mid Range ---
  {
    id: "b6",
    title: "City Commuter 300",
    subtitle: "$90/week",
    price: 90,
    status: "Upcoming",
    startDate: "2026-03-10",
    endDate: "2026-03-20",
    meta: "Mar 10 - Mar 20",
    type: BikeType.CITY,
    isVerified: true,
    rating: 4.5,
    reviewCount: 210,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[1],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b7",
    title: "Hybrid Explorer",
    subtitle: "$105/week",
    price: 105,
    status: "Active",
    startDate: "2026-02-05",
    endDate: "2026-02-12",
    meta: "Feb 05 - Feb 12",
    type: BikeType.HYBRID,
    isVerified: false,
    rating: 4.3,
    reviewCount: 56,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[2],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b8",
    title: "Bolt Runner",
    subtitle: "$130/week",
    price: 130,
    status: "Upcoming",
    startDate: "2026-04-01",
    endDate: "2026-04-10",
    meta: "Apr 01 - Apr 10",
    type: BikeType.ROAD,
    isVerified: true,
    rating: 4.6,
    reviewCount: 78,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[3],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b9",
    title: "Family Hauler",
    subtitle: "$190/week",
    price: 190,
    status: "Upcoming",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    meta: "Mar 15 - Mar 22",
    type: BikeType.CARGO,
    isVerified: true,
    rating: 4.4,
    reviewCount: 12,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[0],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b10",
    title: "Trail Blazer Entry",
    subtitle: "$120/week",
    price: 120,
    status: "Active",
    startDate: "2026-02-20",
    endDate: "2026-02-25",
    meta: "Feb 20 - Feb 25",
    type: BikeType.MOUNTAIN,
    isVerified: false,
    rating: 4.2,
    reviewCount: 30,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[1],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b11",
    title: "Metro Zoom",
    subtitle: "$85/week",
    price: 85,
    status: "Upcoming",
    startDate: "2026-03-05",
    endDate: "2026-03-12",
    meta: "Mar 05 - Mar 12",
    type: BikeType.CITY,
    isVerified: true,
    rating: 4.7,
    reviewCount: 300,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[2],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b12",
    title: "Weekend Warrior",
    subtitle: "$115/week",
    price: 115,
    status: "Active",
    startDate: "2026-02-01",
    endDate: "2026-02-03",
    meta: "Feb 01 - Feb 03",
    type: BikeType.HYBRID,
    isVerified: false,
    rating: 4.1,
    reviewCount: 22,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[3],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b13",
    title: "Speedster 2000",
    subtitle: "$160/week",
    price: 160,
    status: "Upcoming",
    startDate: "2026-02-25",
    endDate: "2026-03-01",
    meta: "Feb 25 - Mar 01",
    type: BikeType.ROAD,
    isVerified: true,
    rating: 4.5,
    reviewCount: 45,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[0],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b14",
    title: "Grocery Getter",
    subtitle: "$175/week",
    price: 175,
    status: "Upcoming",
    startDate: "2026-02-12",
    endDate: "2026-02-14",
    meta: "Feb 12 - Feb 14",
    type: BikeType.CARGO,
    isVerified: true,
    rating: 4.6,
    reviewCount: 18,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[1],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b15",
    title: "Eco Cruiser",
    subtitle: "$95/week",
    price: 95,
    status: "Active",
    startDate: "2026-02-18",
    endDate: "2026-02-22",
    meta: "Feb 18 - Feb 22",
    type: BikeType.CITY,
    isVerified: false,
    rating: 4.0,
    reviewCount: 110,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[2],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },

  // --- GROUP C: Budget / Older ---
  {
    id: "b16",
    title: "Budget Beater",
    subtitle: "$60/week",
    price: 60,
    status: "Active",
    startDate: "2026-02-10",
    endDate: "2026-02-15",
    meta: "Feb 10 - Feb 15",
    type: BikeType.CITY,
    isVerified: false,
    rating: 3.5,
    reviewCount: 14,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[3],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b17",
    title: "Rusty Trusty",
    subtitle: "$55/week",
    price: 55,
    status: "Active",
    startDate: "2026-01-29",
    endDate: "2026-02-05",
    meta: "Jan 29 - Feb 05",
    type: BikeType.HYBRID,
    isVerified: false,
    rating: 2.8,
    reviewCount: 5,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[0],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b18",
    title: "Old School Electric",
    subtitle: "$70/week",
    price: 70,
    status: "Upcoming",
    startDate: "2026-03-20",
    endDate: "2026-03-28",
    meta: "Mar 20 - Mar 28",
    type: BikeType.ROAD,
    isVerified: false,
    rating: 3.2,
    reviewCount: 8,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[1],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b19",
    title: "Heavy Haul (Gen 1)",
    subtitle: "$100/week",
    price: 100,
    status: "Upcoming",
    startDate: "2026-04-10",
    endDate: "2026-04-20",
    meta: "Apr 10 - Apr 20",
    type: BikeType.CARGO,
    isVerified: false,
    rating: 3.8,
    reviewCount: 20,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[2],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  },
  {
    id: "b20",
    title: "Mountain Base",
    subtitle: "$80/week",
    price: 80,
    status: "Active",
    startDate: "2026-02-01",
    endDate: "2026-02-08",
    meta: "Feb 01 - Feb 08",
    type: BikeType.MOUNTAIN,
    isVerified: false,
    rating: 3.9,
    reviewCount: 25,
    image: require("../assets/images/SplashLogo.png"),
    supplier: SUPPLIERS[3],
    features: { battery: true, brakes: true, lights: true, tyres: true }
  }
];